doc-valid-idents = [
  "Cloud9",
  "HLC",
  "MVCC",
  "SQL",
  "KV",
  "TrueTime",
  "CDC",
  "WASM",
  "WAL",
  "Raft",
  "Paxos",
  "TxIR",
  "CDI",
  "TSO",
  ".." # Include the defaults
]

disallowed-types = [
  "std::fs::File",
  "std::fs::OpenOptions",
  "std::fs::ReadDir",
  "std::fs::DirEntry",
  "tokio::fs::File",
  "tokio::fs::OpenOptions",
  "tokio::fs::ReadDir",
  "tokio::fs::DirEntry",
  "std::time::SystemTime",
  "std::time::Instant",
]

disallowed-methods = [
  "std::fs::canonicalize",
  "std::fs::copy",
  "std::fs::create_dir",
  "std::fs::create_dir_all",
  "std::fs::metadata",
  "std::fs::read",
  "std::fs::read_dir",
  "std::fs::read_link",
  "std::fs::read_to_string",
  "std::fs::remove_dir",
  "std::fs::remove_dir_all",
  "std::fs::remove_file",
  "std::fs::rename",
  "std::fs::write",
  "tokio::fs::canonicalize",
  "tokio::fs::copy",
  "tokio::fs::create_dir",
  "tokio::fs::create_dir_all",
  "tokio::fs::metadata",
  "tokio::fs::read",
  "tokio::fs::read_dir",
  "tokio::fs::read_link",
  "tokio::fs::remove_dir",
  "tokio::fs::remove_dir_all",
  "tokio::fs::remove_file",
  "tokio::fs::rename",
  "tokio::fs::write",
  "std::os::unix::fs::symlink",
  { path = "std::os::windows::fs::symlink_dir", allow-invalid = true },
  { path = "std::os::windows::fs::symlink_file", allow-invalid = true },
  "tokio::fs::symlink",
  { path = "tokio::fs::symlink_dir", allow-invalid = true },
  { path = "tokio::fs::symlink_file", allow-invalid = true },
  "std::thread::sleep",
]
