(ns cloud9.jepsen
  (:require [cheshire.core :as json]
            [clj-commons.slingshot :refer [throw+ try+]]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.tools.logging :refer [info]]
            [jepsen [cli :as cli]
                    [client :as client]
                    [checker :as checker]
                    [control :as c]
                    [db :as db]
                    [generator :as gen]
                    [independent :as independent]
                    [random :as rand]
                    [tests :as tests]]
            [jepsen.control.util :as cu]
            [jepsen.checker.timeline :as timeline]
            [jepsen.os.debian :as debian]
            [knossos.model :as model]
            [org.httpkit.client :as http])
  (:import (java.nio.charset StandardCharsets)
           (java.util Base64))
  (:gen-class))

(def dir "/opt/cloud9")
(def upload-path "/tmp/c9")
(def binary (str dir "/c9"))
(def config-file (str dir "/cloud9.toml"))
(def data-dir (str dir "/data"))
(def logfile (str dir "/cloud9.log"))
(def pidfile (str dir "/cloud9.pid"))
(def kv-service "cloud9.kv.v1.KvService")
(def kv-namespace "jepsen")

(defn canonical-path
  [path]
  (.getCanonicalPath (io/file path)))

(defn node-id
  [test node]
  (get (zipmap (:nodes test) (range)) node))

(defn peer-config
  [test]
  (->> (:nodes test)
       (map (fn [node]
              (str "  { id = " (node-id test node)
                   ", host = \"" node "\""
                   ", raft_port = " (:raft-port test)
                   " }")))
       (str/join ",\n")))

(defn node-config
  [test node]
  (str "# Generated by Cloud9 Jepsen.\n"
       "[node]\n"
       "id = " (node-id test node) "\n"
       "host = \"" node "\"\n"
       "client_port = " (:client-port test) "\n"
       "raft_port = " (:raft-port test) "\n"
       "\n"
       "[storage]\n"
       "data_dir = \"" data-dir "\"\n"
       "\n"
       "[cluster]\n"
       "peers = [\n"
       (peer-config test)
       "\n]\n"))

(defn install-node!
  [test node]
  (c/upload (:binary test) upload-path)
  (c/su
    (c/exec :rm :-rf dir)
    (c/exec :mkdir :-p dir data-dir)
    (c/exec :mv upload-path binary)
    (c/exec :chmod :+x binary)
    (c/exec :printf "%s" (node-config test node) :> config-file)))

(defn ensure-running!
  [node]
  (Thread/sleep 1000)
  (when-not (cu/daemon-running? pidfile)
    (throw+ {:type    ::cloud9-exited
             :node    node
             :pidfile pidfile
             :logfile logfile
             :message "cloud9 exited after start; c9 start must run a long-lived DB service"})))

(defn start-node!
  [test node]
  (c/su
    (cu/start-daemon!
      {:logfile logfile
       :pidfile pidfile
       :chdir   dir}
      binary
      "--no-color"
      "--no-progress"
      "start"
      "--config"
      config-file))
  (ensure-running! node))

(defn stop-node!
  []
  (c/su
    (cu/stop-daemon! pidfile)
    (c/exec :rm :-rf dir upload-path)))

(defn cloud9-db
  []
  (reify
    db/DB
    (setup! [_ test node]
      (info node "installing cloud9")
      (install-node! test node)
      (start-node! test node))

    (teardown! [_ _test _node]
      (stop-node!))

    db/Kill
    (kill! [_ _test _node]
      (c/su (cu/stop-daemon! pidfile)))

    (start! [_ test node]
      (start-node! test node))

    db/LogFiles
    (log-files [_ _test _node]
      {logfile     "cloud9.log"
       config-file "cloud9.toml"})))

(defn rpc-url
  [test node method]
  (str "http://" node ":" (:client-port test) "/" kv-service "/" method))

(defn rpc!
  [test node method body]
  (let [{:keys [status body error]} @(http/post (rpc-url test node method)
                                                {:headers            {"content-type" "application/json"}
                                                 :body               (json/generate-string body)
                                                 :connection-timeout 5000
                                                 :socket-timeout     5000})
        decoded (when-not (str/blank? body)
                  (json/parse-string body true))]
    (when error
      (throw+ {:type ::rpc-error
               :node node
               :method method
               :error error}))
    (if (<= 200 status 299)
      decoded
      (throw+ {:type ::rpc-error
               :node node
               :method method
               :status status
               :body decoded}))))

(defn encode-value
  [value]
  (.encodeToString (Base64/getEncoder)
                   (.getBytes (json/generate-string value)
                              StandardCharsets/UTF_8)))

(defn decode-value
  [^String body]
  (let [bytes (.decode ^java.util.Base64$Decoder (Base64/getDecoder) body)]
    (json/parse-string (String. ^bytes bytes StandardCharsets/UTF_8)
                       true)))

(defn kv-key
  [k]
  (str "register/" k))

(defn register-write
  [_ _]
  {:type  :invoke
   :f     :write
   :value (independent/tuple 0 (rand/long 5))})

(defn register-read
  [_ _]
  {:type  :invoke
   :f     :read
   :value (independent/tuple 0 nil)})

(defn register-cas
  [_ _]
  {:type  :invoke
   :f     :cas
   :value (independent/tuple 0 [(rand/long 5) (rand/long 5)])})

(defn next-sequence!
  [sequence]
  (str (swap! sequence inc)))

(defn register-session!
  [test node]
  (:clientId (rpc! test node "RegisterSession" {})))

(defn status!
  [test node]
  (rpc! test node "Status" {}))

(defn current-leader
  [test]
  (some (fn [node]
          (try+
            (when (= "leader" (:mode (status! test node)))
              node)
            (catch [:type ::rpc-error] _
              nil)))
        (:nodes test)))

(defn await-leader!
  [test]
  (loop [attempts 100]
    (if-let [leader (current-leader test)]
      leader
      (if (pos? attempts)
        (do
          (Thread/sleep 100)
          (recur (dec attempts)))
        (throw+ {:type    ::no-leader
                 :message "no Cloud9 Raft leader elected"})))))

(defn get-value!
  [test node k]
  (rpc! test node "Get" {:namespace kv-namespace
                         :key       (kv-key k)}))

(defn put-value!
  [test node session sequence k value preconditions]
  (rpc! test node "Put" (merge {:clientId session
                                :sequence (next-sequence! sequence)
                                :namespace kv-namespace
                                :key      (kv-key k)
                                :body     (encode-value value)}
                               preconditions)))

(defn read-op
  [test node op k]
  (try+
    (let [entry (get-value! test node k)]
      (assoc op
             :type :ok
             :value (independent/tuple k (decode-value (:body entry)))))
    (catch [:type ::rpc-error] e
      (if (= 404 (:status e))
        (assoc op :type :ok :value (independent/tuple k nil))
        (throw+ e)))))

(defn cas-op
  [test node session sequence op k from to]
  (try+
    (if (nil? from)
      (do (put-value! test node session sequence k to {:ifNoneMatch true})
          (assoc op :type :ok))
      (let [entry (get-value! test node k)]
        (if (not= from (decode-value (:body entry)))
          (assoc op :type :fail)
          (do (put-value! test node session sequence k to {:ifMatch (:etag entry)})
              (assoc op :type :ok)))))
    (catch [:type ::rpc-error] e
      (if (#{400 404 409 412} (:status e))
        (assoc op :type :fail)
        (throw+ e)))))

(defrecord KvClient [node session sequence]
  client/Client
  (open! [this test node]
    (let [leader (await-leader! test)]
      (assoc this
           :node leader
           :session (register-session! test leader)
           :sequence (atom 0))))

  (setup! [_ _test])

  (invoke! [_ test op]
    (let [[k value] (:value op)]
      (case (:f op)
        :read  (read-op test node op k)
        :write (do (put-value! test node session sequence k value {})
                   (assoc op :type :ok))
        :cas   (let [[from to] value]
                 (cas-op test node session sequence op k from to)))))

  (teardown! [_ _test])

  (close! [_ _test])

  client/Reusable
  (reusable? [_ _test]
    true))

(defn kv-workload
  [opts]
  {:checker   (independent/checker
                (checker/compose
                  {:linearizable (checker/linearizable
                                   {:model (model/cas-register)})
                   :timeline     (timeline/html)}))
   :client    (KvClient. nil nil nil)
   :generator (cond->> (gen/clients
                         (gen/mix [register-read register-write register-cas register-cas]))
                (pos? (:stagger opts)) (gen/stagger (:stagger opts))
                (:time-limit opts) (gen/time-limit (:time-limit opts)))})

(defn cloud9-test
  [opts]
  (merge tests/noop-test
         opts
         (kv-workload opts)
         {:name            "cloud9 db"
          :pure-generators true
          :os              debian/os
          :db              (cloud9-db)}))

(def cli-opts
  [[nil "--binary PATH" "Local c9 binary to upload"
    :default "../target/release/c9"
    :parse-fn canonical-path]
   [nil "--client-port PORT" "Cloud9 client port on each node"
    :default 19090
    :parse-fn parse-long]
   [nil "--raft-port PORT" "Cloud9 Raft peer port on each node"
    :default 19091
    :parse-fn parse-long]
   [nil "--stagger SECONDS" "Average seconds between generated operations"
    :default 0.01
    :parse-fn parse-double]])

(defn -main
  [& args]
  (cli/run! (merge (cli/single-test-cmd {:test-fn  cloud9-test
                                         :opt-spec cli-opts})
                   (cli/serve-cmd))
            args))
